### ISSUE TITLE
Real time anomaly detection

### ISSUE THREAD

**Issue by casaltenburg** [ankane/AnomalyDetection.rs#4]
Do you think this could be easily implemented for real time anomaly detection?

**Comment by ankane** [comment]
Hey @casaltenburg, this would be great, but unfortunately, real-time detection isn't covered in the original paper / implementation and there aren't any ideas in the issue tracker (https://github.com/twitter/AnomalyDetection/issues/75 and https://github.com/twitter/AnomalyDetection/issues/91).

[This paper](https://link.springer.com/article/10.1007%2Fs10586-021-03236-0) published last year may have a way, but haven't read it yet.

**Comment by ankane** [comment]
Added to #1
