### ISSUE TITLE
Addition of 'only_last' flag

### ISSUE THREAD

**Issue by jmwill86** [ankane/AnomalyDetection.rs#5]
In the Twitter/X article this is based off there's a 'only_last' flag that only shows anomalies from the last period, but I can't see this option in this library.

I know this can currently be done on the callers side, but would it be cleaner and beneficial to have this as an option added?

I'm willing to try and add this functionality if it's something that'd be of use?

**Comment by ankane** [comment]
Hi @jmwill86, from my understanding, it doesn't save any computation and is mostly used to improve plotting, so I don't think it's worth adding.
